/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/models/WawaOffice.glb 
*/

import React, { useLayoutEffect, useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import { gsap } from 'gsap';
import { useFrame } from '@react-three/fiber';

export const FLOOR_HEIGHT = 2.3;
export const NB_FLOORS = 3;

export function Office(props) {
  const { nodes, materials } = useGLTF('./models/WawaOffice.glb')
  //添加引用
  const ref = useRef();
  const tl = useRef();

  //添加滚动
  const scroll = useScroll();

  //添加帧
  useFrame(() => {
    //添加滚动监听
    tl.current.seek(scroll.offset * tl.current.duration());
  });

  //添加动画
  useLayoutEffect(() => {
    //添加时间线
    tl.current = gsap.timeline();

    //添加滚动监听
    tl.current.to(
      //添加引用 @position: 位置
      ref.current.position,
      {
        //添加滚动 @duration: 持续时间 @y: y轴
        duration:2,
        y: -FLOOR_HEIGHT * (NB_FLOORS - 1),
      },
      0
    );
  }, []);
  
  return (
    //添加组 @dispose: 是否销毁 @ref: 引用
    <group {...props} dispose={null} ref={ref}>
      <mesh geometry={nodes['01_office'].geometry} material={materials['01']} />
      <mesh geometry={nodes['02_library'].geometry} material={materials['02']} position={[0, 2.114, -2.23]} />
      <mesh geometry={nodes['03_attic'].geometry} material={materials['03']} position={[-1.97, 4.227, -2.199]} />
    </group>
  )
}

useGLTF.preload('./models/WawaOffice.glb')
